# Generated by Django 4.1.4 on 2022-12-14 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theater_info', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffmember',
            old_name='birthplace',
            new_name='birth_city',
        ),
        migrations.AddField(
            model_name='staffmember',
            name='birth_country',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='birth_prefecture',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='stagename',
            name='associated_staff_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='theater_info.staffmember'),
        ),
    ]
