# Generated by Django 4.1.4 on 2022-12-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater_info', '0002_rename_birthplace_staffmember_birth_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='given_name_romaji',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='birth_country',
            field=models.CharField(blank=True, default='日本国', max_length=255),
        ),
    ]
